name: Test checkout

on:
  push:

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test default checkout
        uses: ./
        with:
          checkout_dir: step1

      - name: Directory exists
        run: |
          if [ ! -d ./step1 ]; then
            echo '::error:: Should be able to be checked out'
            exit 1
          fi

      - name: Test checkout with branch_name as main
        uses: ./
        with:
          branch_name: main
          checkout_dir: step2

      - name: Directory exists
        run: |
          if [ ! -d ./step2 ]; then
            echo '::error:: Should be able to be checked out'
            exit 1
          fi

      - name: Test checkout with branch_name as refs/heads/main
        uses: ./
        with:
          branch_name: refs/heads/main
          checkout_dir: step3

      - name: Directory exists
        run: |
          if [ ! -d ./step3 ]; then
            echo '::error:: Should be able to be checked out'
            exit 1
          fi

      - name: Test checkout and no depth option
        uses: ./
        with:
          depth: ''
          checkout_dir: step4

      - name: Directory exists
        run: |
          if [ ! -d ./step4 ]; then
            echo '::error:: Should be able to be checked out'
            exit 1
          fi

      - name: Test dont checkout when env.ACT is presented.
        uses: ./
        env:
          ACT: 1
        with:
          depth: ''
          checkout_dir: step5

      - name: Directory does not exist
        run: |
          if [ -d ./step5 ]; then
            echo '::error:: Should not be able to be checked out, when ACT environment is exists'
            exit 1
          fi

      - name: Test Write author to .git/config
        uses: ./
        with:
          depth: ''
          checkout_dir: step6

      - name: Have user.name and user.email on .git/config?
        run: |
          set -xe
          pwd
          ls -al
          pushd step6
            if [ "${GITHUB_ACTOR}" != "$(git config --local --get user.name)" ]; then
              echo '::error:: "git config --local --get user.name" Should be equal' "$GITHUB_ACTOR"
              exit 1
            fi
            if [ "${GITHUB_ACTOR}@users.noreply.github.com" != "$(git config --local --get user.email)" ]; then
              echo '::error:: "git config --local --get user.email" Should be equal' "$GITHUB_ACTOR@users.noreply.github.com"
              exit 1
            fi
          popd
